project:
  type: book

book:
  title: "frmAI_help"
  author: "Han-Teng Liao"
  date: "07/11/2025"
  #chapters:

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
#  pdf:
#    documentclass: scrreprt