encoding: "UTF-8"
lang: zh-hant

project:
  type: book
  # Define the output directory that will contain the language subfolders
  output-dir: _book/zht

#language: _language-zh-hant.yml 

book:
  # The base list of chapters (Quarto will look for the language-specific version)
  title: "Framing AI"
  author: "Han-Teng Liao"
  date: "07/11/2025"
  chapters:
    - references.zh-hant.qmd

bibliography: references.bib
resources:
  - styles.css

format:
  html:
    theme:
      - cosmo
      - brand
    lang: zh-Hant  # zh-Hant<-- This sets the <html lang="..."> attribute
    css: styles.css
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "ã€œğŸ“–æœ¬é ç« ç¯€ç›®éŒ„ğŸ“‘ã€œ"
    section-title-appendices: "ğŸ”–é™„éŒ„èˆ‡ç­†è¨˜"
    # âœ… æ­£ç¢ºçš„éµå:
    toc-title-document: "ã€œæœ¬é ç« ç¯€ç›®éŒ„ã€œ"
    crossref-nte-prefix: "è¨»é‡‹"
    crossref-nte-title: "è¨»é‡‹"
    crossref-tip-prefix: "æç¤º"
    crossref-tip-title: "æç¤º"
    callout-important-title: "è¦é»"
    number-sections: true # enable right-hand TOC
    number-depth: 4
    custom-elements:
      model:
        text: "æ¨¡å‹"
        prefix: "mod" 
      taxonomy:
        text: "åˆ†é¡"
        prefix: "tax"
#  pdf:
#    documentclass: scrreprt