encoding: "UTF-8"
lang: zh-hant

project:
  type: website #book
  # Define the output directory that will contain the language subfolders
  output-dir: _book/zht

language: _language-zh-hant.yml 
#book:
#  author: "å»–æ¼¢é¨°"
website:
  navbar:
    right:
      - toggle
  title: "æ¡†æ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Š"
  sidebar:
    style: "docked"
    #style: "floating"
    search: true
    collapse-level: 1
    section-numbers: true
    contents:
      - section: "å°è¨€"
        contents:
          - index.zh-hant.md
          - notes-mental_fill-in.zh-hant.md
          - notes-constructive_fill-in.zh-hant.md
      - section: "01----problematics.zh-hant.md"
        contents:
          - 01-01-Turing_Test.zh-hant.md
          - 01-02-Chinese_Room.zh-hant.md
          - 01-03-Symbol_Grounding_Problem.zh-hant.md
          - 01-04-Frame_Problem.zh-hant.md
          - 01-05-Gestalt_Psychology.zh-hant.md
          - 01-06-Alignment_Control_Problem.zh-hant.md
          - 01-07-Language_Games.zh-hant.md
  page-footer:
    left: |
      ã€Šæ¡†æ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Šã€‹
       (é å°ç‰ˆ) Han-Teng Liao
    right: |
      åˆ«åã€Šé“ï¼ç›œæ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Šã€‹
      æœ¬ç«™ä½¿ç”¨ <a href="https://quarto.org/">Quarto</a> è£½ä½œã€‚
  # cover-image: cover.png ?for book project
  # favicon: cover.png ?for book project
  repo-url: https://github.com/hanteng/frmAI_help/
  repo-actions: [edit]
  # downloads: [pdf, epub]  ? for book project
  # sharing: [linkedin, twitter, facebook] ? for book project

bibliography: references.bib
format:
  html:
    lang: zh-Hant  # zh-Hant<-- This sets the <html lang="..."> attribute
    css: styles.css
    custom-elements:
      model:
        text: "æ¨¡å‹"
        prefix: "mod" 
      taxonomy:
        text: "åˆ†é¡"
        prefix: "tax"
    toc-title: "ã€œğŸ“–æœ¬é ç« ç¯€ğŸ“‘ã€œ"
    section-title-appendices: "ğŸ”–é™„éŒ„èˆ‡ç­†è¨˜"
    # âœ… æ­£ç¢ºçš„éµå:
    #toc-title-document: "ã€œæœ¬é ç« ç¯€ç›®éŒ„ã€œ"
    crossref-nte-prefix: "è¨»é‡‹"
    crossref-nte-title: "è¨»é‡‹"
    crossref-tip-prefix: "æç¤º"
    crossref-tip-title: "æç¤º"
    callout-important-title: "è¦é»"
#  pdf:
#    documentclass: scrreprt