encoding: "UTF-8"
lang: en

project:
  type: website
  # Define the output directory that will contain the language subfolders
  output-dir: _book/en

book:
  # The base list of chapters (Quarto will look for the language-specific version)
  title: "Framing AI"
  author: "Han-Teng Liao"
  date: "07/11/2025"
  chapters:
    - file: index.en.qmd 
    - references.en.qmd   

bibliography: references.bib
resources:
  - styles.css

format:
  html:
    lang: en
    css: styles.css
    custom-elements:
      model:
        text: "Models"
        prefix: "mod" 
      taxonomy:
        text: "Taxonomy"
        prefix: "tax"
    number-sections: true # enable right-hand TOC
    number-depth: 4
    toc: true
    toc-depth: 4
    toc-location: right
#  pdf:
#    documentclass: scrreprt



