project:
  type: book
  # --- ADD THIS SECTION ---
  resources:
    - CNAME
  # -------------------------

book:
  title: "frmAI_help"
  author: "Han-Teng Liao"
  date: "07/11/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
#  pdf:
#    documentclass: scrreprt