encoding: "UTF-8"
lang: zh-hant

project:
  type: book
  # Define the output directory that will contain the language subfolders
  output-dir: _book/zht

language: _language-zh-hant.yml 
book:
  title: "æ¡†æ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Š"
  author: "å»–æ¼¢é¨°"
  date: "18/08/2025"
  chapters:
    - file: index.zh-hant.md
    - file: notes-mental_fill-in.zh-hant.md
    - file: notes-constructive_fill-in.zh-hant.md
    - part: 01----problematics.zh-hant.md
      chapters:
        - file: 01-01-Turing_Test.zh-hant.md
          id: sec-turing-test
        - file: 01-02-Chinese_Room.zh-hant.md
          id: sec-chinese-room
        - file: 01-03-Symbol_Grounding_Problem.zh-hant.md
          id: sec-symbol-grounding-problem
        - file: 01-04-Frame_Problem.zh-hant.md
          id: sec-frame-problem
        - file: 01-05-Gestalt_Psychology.zh-hant.md
          id: sec-gestalt-psychology
        - file: 01-06-Alignment_Control_Problem.zh-hant.md
          id: sec-alignment-control-problem
        - file: 01-07-Language_Games.zh-hant.md
          id: sec-language-games
  sidebar:
    search: true
    style: "docked"
    #style: "floating"
    collapse-level: 1
    section-numbers: true
  page-footer:
    left: |
      ã€Šæ¡†æ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Šã€‹
       (é å°ç‰ˆ) Han-Teng Liao
    right: |
      åˆ«åã€Šé“ï¼ç›œæ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Šã€‹
      æœ¬ç«™ä½¿ç”¨ <a href="https://quarto.org/">Quarto</a> è£½ä½œã€‚
  cover-image: cover.png
  favicon: cover.png
  search: true
  repo-url: https://github.com/hanteng/frmAI_help/
  repo-actions: [edit]
  #downloads: [pdf, epub]
  sharing: [linkedin, twitter, facebook]

bibliography: references.bib
resources:
  - styles.css
  - cover.png
format:
  html:
    theme: # dark mode enabled 
      light: [flatly, styles_converge.scss, styles_custom.scss]
      dark:  [darkly, styles_converge.scss, styles_custom.scss]
    respect-user-color-scheme: true
    lang: zh-Hant  # zh-Hant<-- This sets the <html lang="..."> attribute
    css: styles.css
    custom-elements:
      model:
        text: "æ¨¡å‹"
        prefix: "mod" 
      taxonomy:
        text: "åˆ†é¡"
        prefix: "tax"
    number-sections: true # enable right-hand TOC
    number-depth: 4
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "ã€œğŸ“–æœ¬é ç« ç¯€ğŸ“‘ã€œ"
    section-title-appendices: "ğŸ”–é™„éŒ„èˆ‡ç­†è¨˜"
    # âœ… æ­£ç¢ºçš„éµå:
    #toc-title-document: "ã€œæœ¬é ç« ç¯€ç›®éŒ„ã€œ"
    crossref-nte-prefix: "è¨»é‡‹"
    crossref-nte-title: "è¨»é‡‹"
    crossref-tip-prefix: "æç¤º"
    crossref-tip-title: "æç¤º"
    callout-important-title: "è¦é»"
#  pdf:
#    documentclass: scrreprt