project:
  type: website
bibliography: references.bib
resources:
- styles.css
- styles_converge.scss
- styles_custom.scss
- cover.png
format:
  html:
    from: markdown+emoji
    number-sections: true
    number-depth: 4
    toc: true
    toc-depth: 4
    toc-location: right
    respect-user-color-scheme: true
    theme:
      light:
      - flatly
      - light.scss
      - "styles_converge.scss"
      - "styles_custom.scss"
      dark:
      - darkly
      - dark.scss
      - "styles_converge.scss"
      - "styles_custom.scss"
    default-mode: light
    include-after-body: widget_toggle.html

#filters:
#  - quarto-extra-darkmode   # enables dark/light toggle in book projects
# filters: darkmode  ~ no longer need once the 
