encoding: "UTF-8"
lang: en

project:
  type: website
  # Define the output directory that will contain the language subfolders
  output-dir: _book/en

#book:
#  author: "Han-Teng Liao"

website:
  navbar:
    right:
      - toggle
  # The base list of chapters (Quarto will look for the language-specific version)
  title: "Framing AI"
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Introduction"
        contents:
          - file: index.en.qmd
      #- section: "Problematics"

bibliography: references.bib
resources:
  - styles.css

format:
  html:
    lang: en
    css: styles.css
    custom-elements:
      model:
        text: "Models"
        prefix: "mod" 
      taxonomy:
        text: "Taxonomy"
        prefix: "tax"
    number-sections: true # enable right-hand TOC
    number-depth: 4
    toc: true
    toc-depth: 4
    toc-location: right
#  pdf:
#    documentclass: scrreprt



