encoding: "UTF-8"
lang: zh-hant

project:
  type: book
  output-dir: _book/zht

language: _language-zh-hant.yml 

book:
  title: "æ¡†æ™ºæ ¼å±€ï¼š<br/><small>AI è³½å±€æ‰‹å†Š</small>"
  author: "å»–æ¼¢é¨°"
  chapters:
    - index.zh-hant.md
    - notes-mental_fill-in.zh-hant.md
    - notes-constructive_fill-in.zh-hant.md
    - part: "01----problematics.zh-hant.md"
      chapters:
        - 01-01-Turing_Test.zh-hant.md
        - 01-02-Chinese_Room.zh-hant.md
        - 01-03-Symbol_Grounding_Problem.zh-hant.md
        - 01-04-Frame_Problem.zh-hant.md
        - 01-05-Gestalt_Psychology.zh-hant.md
        - 01-06-Alignment_Control_Problem.zh-hant.md
        - 01-07-Language_Games.zh-hant.md

page-footer:
  left: |
    ã€Šæ¡†æ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Šã€‹
     (é å°ç‰ˆ) Han-Teng Liao
  right: |
    åˆ«åã€Šé“ï¼ç›œæ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Šã€‹
    æœ¬ç«™ä½¿ç”¨ <a href="https://quarto.org/">Quarto</a> è£½ä½œã€‚


bibliography: references.bib

format:
  html:
    lang: zh-Hant
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "ã€œğŸ“–æœ¬é ç« ç¯€ğŸ“‘ã€œ"
    number-sections: true
    number-depth: 4
    section-title-appendices: "ğŸ”–é™„éŒ„èˆ‡ç­†è¨˜"
    crossref-nte-prefix: "è¨»é‡‹"
    crossref-nte-title: "è¨»é‡‹"
    crossref-tip-prefix: "æç¤º"
    crossref-tip-title: "æç¤º"
    callout-important-title: "è¦é»"
